/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng-tinymce.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from './tinymce-editor-settings.service';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
class NgTinymceModuleInjector extends import0.NgModuleInjector<import1.NgTinymceModule> {
  _CommonModule_0:import2.CommonModule;
  _NgTinymceModule_1:import1.NgTinymceModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  __TinymceEditorSettingsService_3:import4.TinymceEditorSettingsService;
  constructor(parent:import5.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import6.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _TinymceEditorSettingsService_3():import4.TinymceEditorSettingsService {
    if ((this.__TinymceEditorSettingsService_3 == null)) { (this.__TinymceEditorSettingsService_3 = new import4.TinymceEditorSettingsService()); }
    return this.__TinymceEditorSettingsService_3;
  }
  createInternal():import1.NgTinymceModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._NgTinymceModule_1 = new import1.NgTinymceModule();
    return this._NgTinymceModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.NgTinymceModule)) { return this._NgTinymceModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import4.TinymceEditorSettingsService)) { return this._TinymceEditorSettingsService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgTinymceModuleNgFactory:import0.NgModuleFactory<import1.NgTinymceModule> = new import0.NgModuleFactory(NgTinymceModuleInjector,import1.NgTinymceModule);